<div class="footer-links">
    <a href="<?php echo strip_tags($this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('privacy')
        ->toHtml())?>">Privacy</a>
    <a href="<?php echo strip_tags($this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('terms_of_use')
        ->toHtml())?>">Terms Of Use</a>
    <a href="<?php echo strip_tags($this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('terms_of_sale')
        ->toHtml())?>">Terms of Use</a>
</div>