<div class="container-fluid">
    <div class="banner">
        <div class="img-banner">
            <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('banner')
                ->toHtml();
            ?>
        </div>
        <div class="banner-text">
            <h2>Trusted solutions, personalized service.</h2>
            <p>Griffith Foods Connect is focused on supporting the innovation and success of customer with unique needs and
                specialized appications. Find out how we can help your business today</p>
            <button><a href="#">Contact Us</a></button>
        </div>
    </div>
</div>