<div class="create-form">
    <div class="form-text">
        <h3>Let's Create Better Together</h3>
        <p>Want to get in touch? We'd love to hear from you. Fill out the form and we will reach out to you as soon as
            possible</p>
    </div>
    <div class="form-input">
        <h3>Send Us Your Message</h3>
        <input type="text" name="first_name" class="first_name" placeholder="First Name*">
        <input type="text" name="last_name" class="last_name" placeholder="Last Name*">
        <input type="text" name="company_name" class="company_name" placeholder="Company Name*">
        <input type="number" name="phone_number" class="phone_number" placeholder="Phone*">
        <input type="email" name="email" class="email" placeholder="Email*">
        <textarea name="message" id="message" cols="30" rows="5" class="message" placeholder="Message*"></textarea>
        <input type="submit" name="send" value="Send">
    </div>
</div>