<div class="post">
    <div class="post-image">
        <?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('service_image')
            ->toHtml();
        ?>
    </div>
    <div class="post-text">
        <h3>Personalized Service and Support</h3>
        <p>Griffith Foods Connect was created to delivery the innovative profolio of Griffith. Foods products to
            versatile, artisan customers in North America. Our dedicated team will work to understand your business and
            provide solutions that meet your unique needs</p>
    </div>
</div>

<div class="order-management">
    <div class="order-text">
        <h3>Supply Chain & Order Management</h3>
        <p>Supported by industry-leading technology, our supply chain stragely focus on improving your purchasing
            experience every step of the way. You can rely on us to meet your needs from the moment you place order to
            the time your product arrive</p>
    </div>
    <div class="order-image">
        <?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('order-management-image')
            ->toHtml();
        ?>
    </div>
</div>

<div class="post">
    <div class="post-image">
        <?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('service_image')
            ->toHtml();
        ?>
    </div>
    <div class="post-text">
        <h3>Personalized Service and Support</h3>
        <p>Griffith Foods Connect was created to delivery the innovative profolio of Griffith. Foods products to
            versatile, artisan customers in North America. Our dedicated team will work to understand your business and
            provide solutions that meet your unique needs</p>
    </div>
</div>