<div class="service">
    <div class="service-title">
        Customers We Serve
    </div>
    <div class="service-content">
        <div class="g-content">
            <div class="g-title">
                Foodservice
            </div>
            <div class="g-description">
                Refresh your core menu or create innoviate Limited Time Offer
            </div>
        </div>
        <div class="g-content">
            <div class="g-title">
                Processers
            </div>
            <div class="g-description">
                Refresh your core menu or create innoviate Limited Time Offer
            </div>
        </div>
        <div class="g-content">
            <div class="g-title">
                Retailer
            </div>
            <div class="g-description">
                Refresh your core menu or create innoviate Limited Time Offer
            </div>
        </div>
        <div class="g-content">
            <div class="g-title">
                Quick Service Restaurants
            </div>
            <div class="g-description">
                Refresh your core menu or create innoviate Limited Time Offer
            </div>
        </div>
    </div>
</div>